#@ load("@ytt:data", "data")
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
  namespace: #@ data.values.namespace
spec:
  type: NodePort
  ports:
  - name: "http" 
    port: 80
    targetPort: 80
  selector:
    app: nginx
