#@ load("@ytt:data", "data")
apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: #@ data.values.namespace
  labels:
    app: redis
spec:
  containers:
  - name: redis
    image: redis:6.2.6
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: #@ data.values.namespace
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
