apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kuard
  namespace: default
spec:
  template:
    metadata:
      annotations:
        # Turn off "scale to zero"
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
      - image: gcr.io/kuar-demo/kuard-amd64:blue
