apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: dotnet-sample
  namespace: default
spec:
  tag: harbor.tanzuathome.net/tce/dotnet-sample
  serviceAccountName: kpack-service-account
  builder:
    name: my-builder
    kind: Builder
  source:
    git:
      url: https://github.com/paketo-buildpacks/samples
      revision: main
    subPath: ./dotnet-core/aspnet
