apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer
  namespace: jgb-namespace
spec:
  type: LoadBalancer
  ports:
  - name: "http" 
    port: 80
    targetPort: 80
  selector:
    app: nginx
