apiVersion: v1
kind: Service
metadata:
  name: payment-calculator
  namespace: jgb-namespace
spec:
  selector:
    app: payment-calculator
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080